hibernate:
  hbm2ddl:
    auto: create-drop
  show_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    env:
      show-values: ALWAYS

server:
  forward-headers-strategy: native

spring:
  datasource:
    driverClassName: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create