name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
#      - name: Just the metadata
#        run: ./gradlew :collectReachabilityMetadata
      - name: Assemble with Gradle
        run: ./gradlew assemble
      - name: Test with Gradle
        run: ./gradlew test
      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: |
            **/build/reports/
            **/build/test-results/

  paketo-build-and-push-to-registry:
    runs-on: ubuntu-latest
    needs: build-and-run-tests
    # disabled for now, flyctl will create the image using buildpacks itself, before deploying it
    steps:
      - uses: actions/checkout@v4
      - uses: buildpacks/github-actions/setup-pack@v5.7.4
      - name: Build and publish image with paketo to GHCR
        run: pack build ghcr.io/anthonydahanne/meetups-calendar --env BP_JVM_VERSION=21 --builder paketobuildpacks/builder-jammy-tiny --publish

  deploy-to-fly:
    runs-on: ubuntu-latest
    needs: build-and-run-tests
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy image
        run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}