name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
#      - name: Just the metadata
#        run: ./gradlew :collectReachabilityMetadata
      - name: Assemble with Gradle
        run: ./gradlew assemble
      - name: Test with Gradle
        run: ./gradlew test
      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: |
            **/build/reports/
            **/build/test-results/

  paketo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: buildpacks/github-actions/setup-pack@v5.6.0
      - name: Build image with paketo
        run: pack build meetups-calendar --env BP_JVM_VERSION=21 --builder paketobuildpacks/builder-jammy-full